/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.dave99galloway.cucumbertest

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test
    fun testSomeLibraryMethod() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}


class CucumberLibraryTest {
    @Test
    fun testSomeCucumberLibraryMethod() {
        val classUnderTest = CucumberLibrary()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}