/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gradle.greeting

/**
 * A simple unit test for the 'gradle.greeting.greeting' plugin.
 */
class GradleGreetingPluginTest {
//    @Test
//    fun `plugin registers task`() {
//        // Create a test project and apply the plugin
//        val project = ProjectBuilder.builder().build()
//        project.plugins.apply("gradle.greeting.greeting")
//
//        // Verify the result
//        assertNotNull(project.tasks.findByName("greeting"))
//    }
}
