/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.dave99galloway.cucumbertest

class CucumberLibrary {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
